export const keys = {
  me: ['users', 'me'] as const,
  home: ['home'] as const,
  matches: ['matches'] as const,
  match: (id: string) => ['matches', id] as const,
  live: (id: string) => ['matches', id, 'live'] as const,
  playingXi: (id: string) => ['matches', id, 'playing-xi'] as const,
  matchResult: (id: string) => ['matches', id, 'result'] as const,
  inningsEvents: (inningsId: string) => ['innings', inningsId, 'events'] as const,
  scorers: ['users', 'scorers'] as const,
  scorecard: (id: string) => ['matches', id, 'scorecard'] as const,
  corrections: (id: string) => ['matches', id, 'corrections'] as const,
  overRules: (id: string) => ['matches', id, 'over-rules'] as const,
  teams: ['teams'] as const,
  team: (id: string) => ['teams', id] as const,
  players: ['players'] as const,
  player: (id: string) => ['players', id] as const,
  playerStats: (id: string) => ['players', id, 'statistics'] as const,
  clubs: ['clubs'] as const,
  club: (id: string) => ['clubs', id] as const,
  tournaments: ['tournaments'] as const,
  tournament: (id: string) => ['tournaments', id] as const,
  tournamentRules: (id: string) => ['tournaments', id, 'rules'] as const,
  tournamentHome: (id: string) => ['tournaments', id, 'home-stats'] as const,
  tournamentDashboard: (id: string) => ['tournaments', id, 'dashboard'] as const,
  tournamentPlayerStats: (id: string, playerId: string) => ['tournaments', id, 'players', playerId, 'stats'] as const,
  points: (id: string) => ['tournaments', id, 'points'] as const,
  statistics: (category: string, tournamentId?: string) => ['statistics', category, tournamentId ?? ''] as const,
  search: (q: string) => ['search', q] as const,
  playerSearch: (q: string) => ['players', 'search', q] as const,
  matchAccess: (id: string) => ['matches', id, 'access'] as const,
  tournamentAccess: (id: string) => ['tournaments', id, 'access'] as const,
  accessLogs: (entity: string, id: string) => ['access', 'logs', entity, id] as const,
  peopleSearch: (q: string) => ['users', 'search', q] as const,
  myAssignedMatches: ['users', 'me', 'matches'] as const,
  teamMatches: (id: string) => ['teams', id, 'matches'] as const,
  teamTournaments: (id: string) => ['teams', id, 'tournaments'] as const,
  myTeams: ['users', 'me', 'teams'] as const,
  myTournaments: ['users', 'me', 'tournaments'] as const,
  myPlayedMatches: ['users', 'me', 'played-matches'] as const,
  playerTeams: (id: string) => ['players', id, 'teams'] as const,
  playerMatches: (id: string) => ['players', id, 'matches'] as const,
  playerTournaments: (id: string) => ['players', id, 'tournaments'] as const,
  playerTournamentStats: (id: string, tournamentId: string) => ['players', id, 'tournaments', tournamentId, 'statistics'] as const,
  matchPlayerStats: (matchId: string, playerId: string) => ['matches', matchId, 'players', playerId, 'statistics'] as const,
  accessOverview: ['access', 'overview'] as const,
  invitePeek: (token: string) => ['invitations', token] as const,
  publicConfig: ['config'] as const,
  betaTesters: ['beta', 'testers'] as const,
  betaFeedback: ['beta', 'feedback'] as const,
  betaWelcome: ['beta', 'welcome'] as const,
  fanOverview: (id: string) => ['fan', 'overview', id] as const,
  fanChat: (id: string) => ['fan', 'chat', id] as const,
  fanQuestions: (kind: string, id: string) => ['fan', kind, id] as const,
  fanBoard: (scope: string, id: string) => ['fan', 'board', scope, id] as const,
  fanQuestion: (id: string) => ['fan', 'question', id] as const,
  fanQuiz: (scope: string, id: string) => ['fan', 'quiz', scope, id] as const,
  fanQuizAdmin: (id: string) => ['fan', 'quiz', 'admin', id] as const,
  fanQuizList: (id: string) => ['fan', 'quiz', 'list', id] as const,
  fanQuizResults: (id: string) => ['fan', 'quiz', 'results', id] as const,
  fanProfile: ['fan', 'me'] as const,
  tournamentKnockout: (id: string) => ['tournaments', id, 'knockout'] as const,
  notifications: ['notifications'] as const,
  following: ['follows', 'me'] as const,
  followStatus: (type: string, id: string) => ['follows', 'status', type, id] as const,
};
